import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { Cagliostro, Inter } from '@next/font/google';
import Header from '@/components/Global';
import axios from 'axios';
import Swal from 'sweetalert2';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Navigation, Pagination, Scrollbar, A11y } from 'swiper';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [movies, setMovies] = useState([]);
  const [favorites, setFavorites] = useState([]);
  const [search, setSearch] = useState('');

  useEffect(() => {
    axios
      .get(`https://www.omdbapi.com/?apikey=46e6b1ec&s=${search || 'harry'}`)
      .then((response) => {
        setMovies(response.data.Search);
      })
      .catch((error) => {
        Swal.fire({
          icon: 'error',
          title: 'Oops...',
          text: 'Cannot found the movie!',
          footer: '<a href="">Why do I have this issue?</a>',
        });
      });
  }, [search]);

  useEffect(() => {
    axios
      .get('https://www.omdbapi.com/?apikey=46e6b1ec&y=2022&s=harry')
      .then((response) => {
        setFavorites(response.data.Search);
      })
      .catch((error) => {
        console.log(error);
      });
  }, []);
  return (
    <>
      <Head>
        <title>IMBd KW Super</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        onSubmit={(e) => {
          e.preventDefault();
          const search = e.target.search.value;
          console.log('search', search);
          setSearch(search);
        }}
      />
      <main className="text-white bg-black">
        <section className="text-center py-10" id="section1">
          <h2 className="text-2xl mix-blend-difference font-bold mt-10">
            About IMDb KW Super
          </h2>
          <p className="mix-blend-difference mt-10">
            Explore the latest and greatest in the film industry with our
            comprehensive movie section, featuring reviews, trailers, and
            showtimes for the most anticipated releases.
          </p>
        </section>
        <section className="text-center py-10 " id="section2">
          <h2 className="text-2xl mix-blend-difference font-bold mt-10">
            Favorite Movies
          </h2>
          <Swiper
            loop={true}
            autoplay={{ delay: 10000, disableOnInteraction: false }}
            slidesPerView={1}
            spaceBetween={5}
            grabCursor={true}
            className=" mt-10 w-96"
          >
            {favorites.map((favorite, index) => (
              <SwiperSlide key={index} className="flex px-5">
                <div className="flex flex-col items-center border border-white rounded-md">
                  <div className="bg-yellow-400 w-full text-black py-2 px-1">
                    {favorite.Title}
                  </div>
                  <Image
                    src={`${favorite.Poster}`}
                    width="200"
                    height="300"
                    alt="poster"
                    className="w-full object-cover"
                  />
                  <div className="flex justify-around w-full my-5">
                    <p className="text-white">Year: {favorite.Year}</p>
                    <p>Type: {favorite.Type}</p>
                  </div>
                  <button
                    className="bg-blue-400 mb-5 px-2 py-1 rounded-md"
                    type="button"
                    onClick={async () => {
                      const res = await axios.get(
                        `https://www.omdbapi.com/?apikey=46e6b1ec&i=${favorite.imdbID}`
                      );
                      console.log(res.data);

                      Swal.fire({
                        imageUrl: `${res.data.Poster}`,
                        imageHeight: 500,
                        imageWidth: 300,
                        imageAlt: 'A tall image',
                        title: `${res.data.Title}`,
                        html: `
                    <div style="text-align: left">
                    <p><span style="font-weight:bold">Rated:</span> &#11088; ${
                      res.data.Ratings.length === 0
                        ? 'N/A'
                        : res.data.Ratings[0].Value
                    }</p>
                    <p><span style="font-weight:bold">Year:</span> ${
                      res.data.Year
                    }</p>
                    <p><span style="font-weight:bold">Genre:</span> ${
                      res.data.Genre
                    }</p>
                    <p><span style="font-weight:bold">Director:</span> ${
                      res.data.Director
                    }</p>
                    <p><span style="font-weight:bold">Actor:</span> ${
                      res.data.Actors
                    }</p>
                    <p><span style="font-weight:bold">Plot:</span> ${
                      res.data.Plot
                    }</p>
                    </div>
                    `,
                      });
                    }}
                  >
                    Show Details
                  </button>
                </div>
              </SwiperSlide>
            ))}
          </Swiper>
        </section>
        <section className="py-10 " id="section3">
          <h2 className="text-2xl mix-blend-difference font-bold mt-10 text-center">
            Movie List
          </h2>
          <div
            className="flex flex-col gap-5 items-center mt-10 md:flex-row md:flex-wrap
          md:justify-center"
          >
            {movies === undefined ? (
              <div className="flex flex-col items-center gap-5 mt-10">
                <h2 className="text-2xl mix-blend-difference font-bold mt-10 text-center">
                  No Movie Found
                </h2>
              </div>
            ) : (
              movies.map((movie, index) => (
                <div
                  key={index}
                  className="flex flex-col items-center border border-white w-80 rounded-md"
                >
                  <div className="bg-yellow-400 w-full text-black py-2 px-1 text-center">
                    {movie.Title}
                  </div>
                  <Image
                    src={`${movie.Poster}`}
                    width="200"
                    height="300"
                    alt="poster"
                    className="w-full object-cover"
                  />
                  <div className="flex justify-around w-full my-5">
                    <p className="text-white">Year: {movie.Year}</p>
                    <p>Type: {movie.Type}</p>
                  </div>
                  <button
                    className="bg-blue-400 mb-5 px-2 py-1 rounded-md"
                    type="button"
                    onClick={async () => {
                      const res = await axios.get(
                        `https://www.omdbapi.com/?apikey=46e6b1ec&i=${movie.imdbID}`
                      );
                      console.log(res.data);

                      Swal.fire({
                        imageUrl: `${res.data.Poster}`,
                        imageHeight: 500,
                        imageWidth: 300,
                        imageAlt: 'A tall image',
                        title: `${res.data.Title}`,
                        html: `
                          <div style="text-align: left">
                          <p><span style="font-weight:bold">Rated:</span> &#11088; ${res.data.Ratings[0].Value}</p>
                          <p><span style="font-weight:bold">Year:</span> ${res.data.Year}</p>
                          <p><span style="font-weight:bold">Genre:</span> ${res.data.Genre}</p>
                          <p><span style="font-weight:bold">Director:</span> ${res.data.Director}</p>
                          <p><span style="font-weight:bold">Actor:</span> ${res.data.Actors}</p>
                          <p><span style="font-weight:bold">Plot:</span> ${res.data.Plot}</p>
                          </div>
                          `,
                      });
                    }}
                  >
                    Show Details
                  </button>
                </div>
              ))
            )}
          </div>
        </section>
      </main>
      <footer className="text-white py-5 text-center bg-slate-800">
        <div>Copyright &copy; 2023 IMDb KW Super</div>
      </footer>
    </>
  );
}
